<Project>
  <PropertyGroup>
    <Version>0.4.1</Version>
    <Authors>Thaylon Lopes</Authors>
    <Company>Thaylon Lopes</Company>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/thaylonlopes/ExtensionLibrary</PackageProjectUrl>
    <RepositoryUrl>https://github.com/thaylonlopes/ExtensionLibrary</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
    <NoWarn>$(NoWarn);1591</NoWarn>
    <PackageIcon>icon.png</PackageIcon>
    <PackageTags>csharp;dotnet;dotnet8;netstandard;extensions;utilities;clean-architecture;zero-allocation</PackageTags>
  </PropertyGroup>


  <ItemGroup Condition="'$(IsPackable)' != 'false'">
    <None Include="$(MSBuildThisFileDirectory)assets\icon.png" Pack="true" PackagePath="" />
  </ItemGroup>

  <!-- Regra de Governança: Testes e Exemplos não geram pacote NuGet nem documentação XML -->
  <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('.Tests')) Or $(MSBuildProjectName.Contains('.Showcase'))">
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
</Project>

