<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net5.0;net6.0;net8.0</TargetFrameworks>
    <Nullable>disable</Nullable>
    <PackageId>TL.StringExtensionsLibrary</PackageId>
    <Description>Projeto de extensão para string</Description>
    <Title>StringExtensionsLibrary</Title>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
