<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net5.0;net6.0;net8.0</TargetFrameworks>
    <Nullable>disable</Nullable>
    <PackageId>TL.CollectionExtensionsLibrary</PackageId>
    <Description>Projeto de extensão para Collection</Description>
    <Title>CollectionExtensionsLibrary</Title>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
</Project>
